export const API_PATHS = {
  books: "/books",
  book: (bookId: number) => `/books/${bookId}`,
  users: "/users",
  user: (userId: number) => `/users/${userId}`,
  loans: "/loans",
  loan: (loanId: number) => `/loans/${loanId}`,
  borrowLoan: "/loans/borrow",
  returnLoan: (loanId: number) => `/loans/${loanId}/return`,
  loanFineSummary: (loanId: number) => `/loans/${loanId}/fine-summary`,
  loanFinePayments: (loanId: number) => `/loans/${loanId}/fine-payments`,
  finePayments: "/fine-payments",
  seed: "/seed",
  importBooks: "/imports/books",
  importUsers: "/imports/users",
  importLoans: "/imports/loans",
  policy: "/settings/policy",
  auditLogs: "/audit/logs",
  authLogin: "/auth/login",
  authMe: "/auth/me",
  myLoans: "/users/me/loans",
  myFinePayments: "/users/me/fine-payments",
} as const;
